### ISSUE TITLE
Game crashes to launcher when starting world with Create Fabric active due to corrupting mob data

### ISSUE THREAD

**Issue by Twig5** [CleverNucleus/Data-Attributes#15]
Game crashes to launcher when starting world with Create Fabric active. Appears to be due to setting a gravity attribute of a mob to null.

https://www.curseforge.com/minecraft/mc-mods/create-fabric

Minecraft Version: 1.18.2
Data Attributes: 1.1.6
Fabric API Version: 0.56.1
Create Fabric version: 0.4.11 Patch 11

Launch done through Curse client. Verified on my more heavily modded profile and a blank profile created to test if any other config settings were causing the issue. New world was created with base settings and cheats turned on. No other settings were touched before created the world. No other mods were installed or had been installed at time of crash.

Based on my limited knowledge of Minecraft modding and looking at several error reports before reporting, it appears that the issue occurs after the world has finished generating and is spawning initial mobs. Some return value is null, corrupting the mob and causing a ticking entity error when trying to call modifyGravity. The issue appears to occur on the first mob to be affected, as the entity in the entity details changes crash by crash.

Internal Server Log:
[latest.log](https://github.com/CleverNucleus/Data-Attributes/files/8971916/latest.log)

Crash Report:
[crash-2022-06-23_18.16.22-server.txt](https://github.com/CleverNucleus/Data-Attributes/files/8971918/crash-2022-06-23_18.16.22-server.txt)

**Comment by CleverNucleus** [comment]
Hi there,
Thank you for the detailed report, I'll look into it.

**Comment by udidifier** [comment]
hi,
getting this exact issue as well, also narrowed it down to the create fabric mod. error mentions modifyGravity

**Comment by udidifier** [comment]
bump with response from Create devs
[https://github.com/Fabricators-of-Create/Create/issues/400](https://github.com/Fabricators-of-Create/Create/issues/400)

**Comment by CleverNucleus** [comment]
Hi there @udidifier,
I can confirm this; I had an interaction earlier on #16 (duplicate) and briefly discussed this. The crash has been mitigated with a null check, but I still need to fix the bug that caused the issue to begin with. I know why the error is happening so progress should not be too slow.

Thanks again for the alert, I'm closing this issue now as it is duplicate.
