### ISSUE TITLE
Minecraft Version Error on 1.2.0

### ISSUE THREAD

**Issue by ardissaps** [CleverNucleus/Data-Attributes#20]
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Data Attributes' (dataattributes) 1.2.0 with version 1.1.6 or later that is compatible with:
		 - minecraft 1.18.2
Unmet dependency listing:
	 - Mod 'Data Attributes' (dataattributes) 1.2.0 requires version 1.19 of 'Minecraft' (minecraft), but only the wrong version is present: 1.18.2!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

The modrinth 1.2.0 files tagged as 1.18.2 compatible
![image](https://user-images.githubusercontent.com/82106625/180336485-46c1a4c4-cc6b-44a8-8b58-74f4386079cc.png)

**Comment by CleverNucleus** [comment]
Oops,
Should be fixed now. Thanks for catching that!

**Comment by ardissaps** [comment]
So, should I downgrade to 1.1.9 if using for my 1.18.2 instance?
