### ISSUE TITLE
latest data attributes breaks playerex on server

### ISSUE THREAD

**Issue by Monster-Zer0** [CleverNucleus/Data-Attributes#28]
![image](https://user-images.githubusercontent.com/5826746/215316182-3871b1d1-7c80-4eb8-b352-eab30ca4e5e1.png)

this only happens if you go straight to a server.

but if you run a single player instance.. then go back into server it works fine.

**Comment by CleverNucleus** [comment]
Hi there,
I've confirmed the issue - latest release of Data Attributes indeed breaks PlayerEx. Will hopefully release a fix in the coming week.
Thanks.

**Comment by CleverNucleus** [comment]
Fixed with latest releases for Minecraft 1.18.2 and 1.19.2.
